
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Update staging server
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    gcloud compute ssh nitin-nodejs-instance-2 --zone=us-central1-a --command='/bin/sh /home/alokwinwork/pull.sh'
